source 'http://rubygems.org'

gem 'activerecord', :require => 'active_record'
gem 'sinatra-activerecord', :require => 'sinatra/activerecord'

gem 'sinatra'
gem 'sqlite3'
gem 'shotgun'
gem 'tux'
gem 'pry'
gem 'pry-nav'
gem 'rake'
gem 'rspec'
gem 'rack-test'
gem 'require_all'