source 'https://rubygems.org'

gem 'activerecord', '~> 5.0', '>= 5.0.0.1'
gem 'sinatra-activerecord'
gem 'sinatra'
gem 'sqlite3', '~> 1.4'
gem 'shotgun'
gem 'tux'
gem 'pry'
gem 'pry-nav'
gem 'rake'
gem 'rspec'
gem 'rack-test'
gem 'database_cleaner', git: 'https://github.com/bmabey/database_cleaner.git'
gem 'require_all'
gem 'json', '>=1.8.3'